#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""TASK-113: prepare the H4/H5/H6/H9 exercise projects and their sessions.

Read-only with respect to everything outside:
    projects/_exercises/ex_nav
    projects/_exercises/ex_audio
    projects/_exercises/ex_rec
    projects/_exercises/ex_particles
    tools/sessions/_exercises/<the same four>

Each project is a copy of the TASK-111 exercise project `ex_grid` (which ships
the C# template, the import cache and the seed PNGs), so no new project skeleton
is invented.  Everything the families need is then generated by the engine's own
API inside `mk_probe.gd` (run headless) exactly like `ex_grid`/`ex_anim` do.

Usage:
    python recovery/work/task113/gen_family_sessions.py prepare
    python recovery/work/task113/gen_family_sessions.py sessions
"""
import io
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
SRC_PROJECT = os.path.join(ROOT, "projects", "_exercises", "ex_grid")
EX = os.path.join(ROOT, "projects", "_exercises")
SESS = os.path.join(ROOT, "tools", "sessions", "_exercises")

# ---------------------------------------------------------------------------
# The scene every exercise project starts from: a Node2D root with
#   * a NavigationRegion2D whose NavigationPolygon carries an outline (the bake
#     tool's own precondition: `generator_bake_from_source_geometry_data` reads
#     `NavigationPolygon::get_outline()`),
#   * a CharacterBody2D "Player" carrying a *drawn* Polygon2D (so a moved player
#     is a pixel change) and a NavigationAgent2D (the H4 move tool's agent path),
#   * a Node2D "Goal" the move tool can be aimed at,
#   * a visible "HUD" Label (the audio/particle families reuse the same scene).
# ---------------------------------------------------------------------------
MOVE_PLAYER_GD = '''extends CharacterBody2D
# TASK-113 exercise: the H9 recording/replay family needs one motion the *game
# process* really performs from input alone. `Input.is_key_pressed` is fed by the
# key events `running_game_play_input_recording` injects through
# `Input::parse_input_event`, so a replay moves this node and the pixel diff and
# `running_game_get_node_properties` both see it.
const SPEED := 180.0

func _physics_process(delta: float) -> void:
	var dx := 0.0
	if Input.is_key_pressed(KEY_RIGHT):
		dx += SPEED * delta
	if Input.is_key_pressed(KEY_LEFT):
		dx -= SPEED * delta
	if dx != 0.0:
		global_position.x += dx
'''

MK_PROBE_GD = '''extends SceneTree

# TASK-113: build the probe scene the H4 (navigation) / H9 (recording) families
# need, using only the engine's own API. See the generator's header.

func _initialize() -> void:
	var script_path := "res://src/move_player.gd"
	var f := FileAccess.open(script_path, FileAccess.WRITE)
	f.store_string("""%s""")
	f.close()

	var root := Node2D.new()
	root.name = "NavRoot"

	var poly := NavigationPolygon.new()
	var outline := PackedVector2Array([
		Vector2(40.0, 40.0), Vector2(760.0, 40.0),
		Vector2(760.0, 560.0), Vector2(40.0, 560.0)])
	poly.add_outline(outline)

	var region := NavigationRegion2D.new()
	region.name = "Region"
	region.navigation_polygon = poly
	root.add_child(region)
	region.owner = root

	var player := CharacterBody2D.new()
	player.name = "Player"
	player.position = Vector2(100.0, 300.0)
	var scr := load(script_path)
	if scr != null:
		player.set_script(scr)
	root.add_child(player)
	player.owner = root

	var drawn := Polygon2D.new()
	drawn.name = "Drawn"
	drawn.polygon = PackedVector2Array([
		Vector2(-12.0, -12.0), Vector2(12.0, -12.0),
		Vector2(12.0, 12.0), Vector2(-12.0, 12.0)])
	drawn.color = Color(0.9, 0.2, 0.2, 1.0)
	player.add_child(drawn)
	drawn.owner = root

	var agent := NavigationAgent2D.new()
	agent.name = "Agent"
	agent.radius = 8.0
	agent.max_speed = 240.0
	player.add_child(agent)
	agent.owner = root

	var goal := Node2D.new()
	goal.name = "Goal"
	goal.position = Vector2(700.0, 300.0)
	root.add_child(goal)
	goal.owner = root

	var hud := Label.new()
	hud.name = "HUD"
	hud.text = "ex"
	hud.position = Vector2(20.0, 20.0)
	root.add_child(hud)
	hud.owner = root

	var packed := PackedScene.new()
	var perr := packed.pack(root)
	var serr := ResourceSaver.save(packed, "res://scenes/main.tscn")
	print("MKNAV pack_err=", perr, " save_err=", serr,
		" outlines=", poly.get_outline_count(), " outline_pts=", outline.size())
	quit()
''' % MOVE_PLAYER_GD

# The audio project needs one stream resource for the player tool to point at.
MK_AUDIO_GD = '''extends SceneTree

# TASK-113: the H5 (audio) family's subjects. `editor_add_audio_player` only
# creates the node; the stream it should play is a project asset, so the same
# script the other families use also writes a Node2D root with a visible HUD and
# the two WAV assets are produced next to it by the generator (real RIFF files,
# imported by `--import`).

func _initialize() -> void:
	var root := Node2D.new()
	root.name = "AudioRoot"

	var hud := Label.new()
	hud.name = "HUD"
	hud.text = "audio"
	hud.position = Vector2(20.0, 20.0)
	root.add_child(hud)
	hud.owner = root

	var packed := PackedScene.new()
	var perr := packed.pack(root)
	var serr := ResourceSaver.save(packed, "res://scenes/main.tscn")
	print("MKAUDIO pack_err=", perr, " save_err=", serr)
	quit()
'''

# The particle project needs one existing GPUParticles2D to write into (the five
# preset/material/gradient writers address a node; `editor_create_particles`
# creates its own five).
MK_PARTICLE_GD = '''extends SceneTree

# TASK-113: the H6 (particle) family's subject scene.

func _initialize() -> void:
	var root := Node2D.new()
	root.name = "PartRoot"

	var seed_particles := GPUParticles2D.new()
	seed_particles.name = "Seed"
	seed_particles.position = Vector2(300.0, 300.0)
	seed_particles.amount = 8
	root.add_child(seed_particles)
	seed_particles.owner = root

	var hud := Label.new()
	hud.name = "HUD"
	hud.text = "particles"
	hud.position = Vector2(20.0, 20.0)
	root.add_child(hud)
	hud.owner = root

	var packed := PackedScene.new()
	var perr := packed.pack(root)
	var serr := ResourceSaver.save(packed, "res://scenes/main.tscn")
	print("MKPART pack_err=", perr, " save_err=", serr)
	quit()
'''

PROJECTS = {
    "ex_nav": ("h4", MK_PROBE_GD),
    "ex_audio": ("h5", MK_AUDIO_GD),
    "ex_rec": ("h9", MK_PROBE_GD),
    "ex_particles": ("h6", MK_PARTICLE_GD),
}


def wav_bytes(path, freq, seconds=0.25, rate=44100):
    """A small mono 16-bit RIFF WAVE: a sine (or silence when freq == 0)."""
    import math
    import struct
    frames = int(rate * seconds)
    data = bytearray()
    for i in range(frames):
        value = 0 if freq == 0 else int(12000 * math.sin(2.0 * math.pi * freq * i / rate))
        data += struct.pack("<h", value)
    out = bytearray()
    out += b"RIFF" + struct.pack("<I", 36 + len(data)) + b"WAVE"
    out += b"fmt " + struct.pack("<IHHIIHH", 16, 1, 1, rate, rate * 2, 2, 16)
    out += b"data" + struct.pack("<I", len(data)) + data
    with open(path, "wb") as handle:
        handle.write(bytes(out))


def prepare():
    for name, (_batch, gd) in PROJECTS.items():
        dst = os.path.join(EX, name)
        if not os.path.isdir(dst):
            shutil.copytree(SRC_PROJECT, dst)
            # The copied template's pong scenes are not this project's subject;
            # mk_probe.gd overwrites scenes/main.tscn right after the import.
            print("copied  %s" % dst)
        else:
            print("kept    %s (already there)" % dst)
        with io.open(os.path.join(dst, "mk_probe.gd"), "w", encoding="utf-8", newline="\n") as h:
            h.write(gd)
        print("wrote   %s/mk_probe.gd" % dst)
    audio_assets = os.path.join(EX, "ex_audio", "assets")
    if not os.path.isdir(audio_assets):
        os.makedirs(audio_assets)
    for i, freq in enumerate((440, 660, 880, 0, 220), 1):
        p = os.path.join(audio_assets, "tone%d.wav" % i)
        if not os.path.isfile(p):
            wav_bytes(p, freq)
        print("wav     %s (%d bytes)" % (p, os.path.getsize(p)))
    return 0


# ---------------------------------------------------------------------------
# The sessions
# ---------------------------------------------------------------------------
class Batch(object):
    def __init__(self, batch, project, run_tag):
        self.batch = batch
        self.project = project
        self.run = "runs/_exercises/%s/%s" % (project, run_tag)
        self.calls = []
        self.manifest = []
        self.readback = []
        self.seq = 0

    def call(self, tool, port, args, intent="ok", note=""):
        self.seq += 1
        tag = "%s-%03d-%s" % (self.batch, self.seq, tool)
        call = {"tag": tag, "port": port, "tool": tool, "arguments": args}
        if note:
            call["note"] = note
        self.calls.append(call)
        self.manifest.append({"tag": tag, "tool": tool, "port": port,
                              "intent": intent, "note": note})
        return tag

    def sleep(self, port, ms, note):
        self.calls.append({"sleep_ms": ms, "port": port, "note": note})

    def readback_of(self, tool, witness, why, expect):
        self.readback.append({"tool": tool, "witness_tool": witness, "run": self.run,
                              "why": why, "expect": expect})

    def write(self):
        out_dir = os.path.join(SESS, self.project)
        if not os.path.isdir(out_dir):
            os.makedirs(out_dir)
        session = {"_comment": "TASK-113 batch %s -- %s" % (self.batch, self.project),
                   "game": self.project, "import": True, "calls": self.calls}
        with io.open(os.path.join(out_dir, "%s-session.json" % self.batch), "w",
                     encoding="utf-8", newline="\n") as h:
            h.write(json.dumps(session, ensure_ascii=False, indent=2) + "\n")
        with io.open(os.path.join(out_dir, "%s-manifest.json" % self.batch), "w",
                     encoding="utf-8", newline="\n") as h:
            h.write(json.dumps({"batch": self.batch, "project": self.project,
                                "calls": self.manifest, "readback": self.readback},
                               ensure_ascii=False, indent=2) + "\n")
        print("batch %s: %d calls, %d readback declarations -> %s"
              % (self.batch, len(self.calls), len(self.readback), out_dir))


def build_h4():
    b = Batch("h4", "ex_nav", "h4-task113")
    b.call("editor_open_scene", "editor", {"path": "res://scenes/main.tscn"}, "setup",
           "the scene every H4 tool addresses")
    # --- editor_setup_navigation_region: 5 ok + 1 probe ---------------------
    for i, args in enumerate([
            {"node_path": ".", "name": "RegionA", "mode": "2d"},
            {"node_path": ".", "name": "RegionB", "mode": "2d", "agent_radius": 6.0},
            {"node_path": ".", "name": "RegionC", "mode": "2d", "cell_size": 0.1},
            {"node_path": "RegionB", "name": "RegionD", "mode": "2d"},
            {"node_path": "RegionC", "name": "RegionE", "mode": "2d", "agent_radius": 12.0}], 1):
        b.call("editor_setup_navigation_region", "editor", args,
               note="setup_navigation_region call %d/5 (a NavigationPolygon resource is created and assigned)" % i)
    b.call("editor_setup_navigation_region", "editor", {"node_path": "NoSuchParent", "mode": "2d"},
           "probe", "parent does not exist")
    # --- editor_setup_navigation_agent: 5 ok + 1 probe ----------------------
    for i, args in enumerate([
            {"node_path": "Player", "agent_type": "2D", "name": "NA1"},
            {"node_path": "Player", "agent_type": "2D", "name": "NA2", "radius": 10.0},
            {"node_path": "Player", "agent_type": "2D", "name": "NA3", "max_speed": 320.0},
            {"node_path": "Goal", "agent_type": "2D", "name": "NA4"},
            {"node_path": "RegionA", "agent_type": "2D", "name": "NA5"}], 1):
        b.call("editor_setup_navigation_agent", "editor", args,
               note="setup_navigation_agent call %d/5" % i)
    b.call("editor_setup_navigation_agent", "editor", {"node_path": "Player", "agent_type": "4D"},
           "probe", "agent_type is a closed set of 2D/3D")
    # --- editor_set_navigation_layers: 5 ok + 2 probes ----------------------
    for i, args in enumerate([
            {"node_path": "Region", "layers": 1},
            {"node_path": "Region", "layers": 3},
            {"node_path": "Player/Agent", "layers": 5},
            {"node_path": "Player/NA1", "layers": 8},
            {"node_path": "RegionC", "layers": 2}], 1):
        b.call("editor_set_navigation_layers", "editor", args,
               note="set_navigation_layers call %d/5 (the written mask is read back by editor_get_navigation_info)" % i)
    b.call("editor_set_navigation_layers", "editor", {"node_path": "Region", "layers": -1},
           "probe", "negative mask is outside the uint32 range")
    b.call("editor_set_navigation_layers", "editor", {"node_path": "HUD", "layers": 1},
           "probe", "a Label has no navigation_layers member")
    # --- editor_bake_navigation_mesh: 5 ok + 1 probe ------------------------
    for i in range(5):
        b.call("editor_bake_navigation_mesh", "editor", {"navigation_region_path": "Region"},
               note="bake %d/5 of the region whose polygon carries an outline" % (i + 1))
    b.call("editor_bake_navigation_mesh", "editor", {"navigation_region_path": "HUD"},
           "probe", "a Label is not a NavigationRegion")
    # --- editor_get_navigation_info: 5 ok + 1 probe -------------------------
    for i, args in enumerate([{}, {"node_path": "Region"}, {"node_path": "Player"},
                              {"node_path": "."}, {"node_path": "RegionC"}], 1):
        b.call("editor_get_navigation_info", "editor", args,
               note="read back the regions/agents/layers written above (%d/5)" % i)
    b.call("editor_get_navigation_info", "editor", {"node_path": "NoSuchNode"},
           "probe", "node does not exist")
    b.call("editor_save_scene", "editor", {}, "setup",
           "persist the baked polygon so the game endpoint loads real navigation data")
    # --- game phase: running_game_move_player_to_target ---------------------
    for i, args in enumerate([
            {"target": {"x": 300.0, "y": 300.0}, "arrival_radius": 25.0},
            {"target": "Goal", "arrival_radius": 25.0},
            {"target": {"x": 500.0, "y": 200.0}, "arrival_radius": 25.0},
            {"target": "Goal", "arrival_radius": 40.0, "run": True},
            {"target": {"x": 200.0, "y": 400.0}, "arrival_radius": 25.0}], 1):
        b.call("running_game_move_player_to_target", "game", args,
               note="move call %d/5; the agent path is the engine's own NavigationServer path" % i)
    b.call("running_game_move_player_to_target", "game", {"target": "NoSuchNode"},
           "probe", "target node does not exist")
    b.call("running_game_get_node_properties", "game",
           {"node_path": "Player", "properties": ["position"]}, "setup",
           "read-back: where the player really ended up after the moves")

    b.readback_of("editor_setup_navigation_region", "editor_get_navigation_info",
                  "the created NavigationRegion2D must appear in editor_get_navigation_info's "
                  "region list with its real class and layer mask", "\"RegionA\"")
    b.readback_of("editor_setup_navigation_agent", "editor_get_navigation_info",
                  "the created NavigationAgent2D must appear in the agent list with the radius "
                  "and max_speed the tool wrote", "\"max_speed\"")
    b.readback_of("editor_set_navigation_layers", "editor_get_navigation_info",
                  "the mask editor_set_navigation_layers wrote must be in the read-back record",
                  "\"navigation_layers\": 2")
    b.readback_of("editor_bake_navigation_mesh", "editor_get_navigation_info",
                  "the bake's own polygon_count must appear in the region record "
                  "(baked: true)", "\"baked\": true")
    b.readback_of("running_game_move_player_to_target", "running_game_get_node_properties",
                  "the player's position after the moves differs from its start (100,300)",
                  "\"position\"")
    b.write()


def build_h5():
    b = Batch("h5", "ex_audio", "h5-task113")
    b.call("editor_open_scene", "editor", {"path": "res://scenes/main.tscn"}, "setup",
           "the scene the audio player node is added to")
    # --- editor_add_audio_bus: 5 ok + 2 probes ------------------------------
    for i, args in enumerate([
            {"name": "Music"}, {"name": "Sfx"}, {"name": "Ambient"},
            {"name": "Voice"}, {"name": "Ui", "after_bus_index": 0}], 1):
        b.call("editor_add_audio_bus", "editor", args,
               note="add_audio_bus call %d/5; the bus list is read back by editor_get_audio_bus_layout" % i)
    b.call("editor_add_audio_bus", "editor", {"name": "Music"},
           "probe", "a bus of that name already exists (the engine would disambiguate it)")
    b.call("editor_add_audio_bus", "editor", {"name": "Bad", "after_bus_index": 99},
           "probe", "after_bus_index is outside the existing bus range")
    # --- editor_add_audio_bus_effect: 5 ok + 2 probes -----------------------
    for i, args in enumerate([
            {"bus_index": 1, "effect_type": "AudioEffectAmplify", "name": "Fx1"},
            {"bus_index": 2, "effect_type": "AudioEffectReverb", "name": "Fx2"},
            {"bus_index": 2, "effect_type": "AudioEffectChorus"},
            {"bus_index": 3, "effect_type": "AudioEffectDelay", "name": "Fx4"},
            {"bus_index": 1, "effect_type": "AudioEffectLimiter", "name": "Fx5"}], 1):
        b.call("editor_add_audio_bus_effect", "editor", args,
               note="add_audio_bus_effect call %d/5" % i)
    b.call("editor_add_audio_bus_effect", "editor", {"bus_index": 1, "effect_type": "Node"},
           "probe", "Node is not an AudioEffect subclass")
    b.call("editor_add_audio_bus_effect", "editor", {"bus_index": 99, "effect_type": "AudioEffectAmplify"},
           "probe", "bus_index does not exist")
    # --- editor_add_audio_player: 5 ok + 1 probe ----------------------------
    for i, args in enumerate([
            {"name": "Ap1", "parent_path": "."},
            {"name": "Ap2", "parent_path": "."},
            {"name": "Ap3"}, {"name": "Ap4"}, {"name": "Ap5"}], 1):
        b.call("editor_add_audio_player", "editor", args,
               note="add_audio_player call %d/5 (the node is read back by editor_get_node_properties)" % i)
    b.call("editor_add_audio_player", "editor", {"name": "ApX", "parent_path": "NoSuchParent"},
           "probe", "parent does not exist")
    # --- editor_get_audio_bus_layout: 5 ok + 1 probe ------------------------
    for i in range(5):
        b.call("editor_get_audio_bus_layout", "editor", {},
               note="read the bus layout the writes above produced (%d/5)" % (i + 1))
    b.call("editor_get_audio_bus_layout", "editor", {"bogus_argument": 1},
           "probe", "out-of-contract argument")
    # --- editor_get_audio_info: 5 ok + 1 probe ------------------------------
    for i in range(5):
        b.call("editor_get_audio_info", "editor", {},
               note="read the audio server state (%d/5)" % (i + 1))
    b.call("editor_get_audio_info", "editor", {"bogus_argument": 1},
           "probe", "out-of-contract argument")
    # --- editor_set_audio_bus_property: 5 ok + 3 probes ---------------------
    for i, args in enumerate([
            {"bus_index": 1, "property": "volume_db", "value": -6.0},
            {"bus_index": 1, "property": "mute", "value": True},
            {"bus_index": 2, "property": "volume_db", "value": -3.0},
            {"bus_index": 2, "property": "solo", "value": False},
            {"bus_index": 3, "property": "volume_db", "value": -12.0}], 1):
        b.call("editor_set_audio_bus_property", "editor", args,
               note="set_audio_bus_property call %d/5 (read back by editor_get_audio_bus_layout)" % i)
    b.call("editor_set_audio_bus_property", "editor", {"bus_index": 1, "property": "no_such_property", "value": 1},
           "probe", "the bus has no such member")
    b.call("editor_set_audio_bus_property", "editor", {"bus_index": 1, "property": "volume_db", "value": "loud"},
           "probe", "volume_db is typed number, not string")
    b.call("editor_set_audio_bus_property", "editor", {"bus_index": 99, "property": "volume_db", "value": 0.0},
           "probe", "bus_index does not exist")
    b.call("editor_get_node_properties", "editor", {"path": "Ap1"}, "setup",
           "read-back: the created AudioStreamPlayer2D node really is in the scene")
    b.call("editor_get_audio_bus_layout", "editor", {}, "setup",
           "read-back: the bus properties written above, from the engine's own layout")

    b.readback_of("editor_add_audio_bus", "editor_get_audio_bus_layout",
                  "the bus editor_add_audio_bus created must appear in the engine's bus layout",
                  "\"Music\"")
    b.readback_of("editor_add_audio_bus_effect", "editor_get_audio_bus_layout",
                  "the effect must appear in the bus's effect list with the engine's class name",
                  "AudioEffectAmplify")
    b.readback_of("editor_add_audio_player", "editor_get_node_properties",
                  "the node editor_add_audio_player created must be in the scene as an "
                  "AudioStreamPlayer2D", "AudioStreamPlayer2D")
    b.readback_of("editor_set_audio_bus_property", "editor_get_audio_bus_layout",
                  "the written volume_db must be the bus's real value in the layout",
                  "\"volume_db\": -6.0")
    b.write()


def build_h6():
    b = Batch("h6", "ex_particles", "h6-task113")
    b.call("editor_open_scene", "editor", {"path": "res://scenes/main.tscn"}, "setup",
           "the scene every particle tool addresses")
    # --- editor_create_particles: 5 ok + 3 probes ---------------------------
    for i, args in enumerate([
            {"name": "P1", "parent_path": "."},
            {"name": "P2", "parent_path": ".", "particle_type": "GPUParticles2D"},
            {"name": "P3", "parent_path": "."},
            {"name": "P4", "parent_path": "."},
            {"name": "P5", "parent_path": "."}], 1):
        b.call("editor_create_particles", "editor", args,
               note="create_particles call %d/5 (a fresh ParticleProcessMaterial is assigned)" % i)
    b.call("editor_create_particles", "editor", {"name": "P1"},
           "probe", "a node of that name already exists")
    b.call("editor_create_particles", "editor", {"name": "Px", "particle_type": "CPUParticles2D"},
           "probe", "CPUParticles2D has no process_material slot")
    b.call("editor_create_particles", "editor", {"name": "Py", "parent_path": "NoSuchParent"},
           "probe", "parent does not exist")
    # --- editor_set_particle_preset: 5 ok + 2 probes ------------------------
    for i, (node, preset) in enumerate([("P1", "fire"), ("P2", "smoke"), ("P3", "magic"),
                                        ("P4", "explosion"), ("P5", "rain")], 1):
        b.call("editor_set_particle_preset", "editor", {"node_path": node, "preset": preset},
               note="set_particle_preset call %d/5 (read back by editor_get_particle_info)" % i)
    b.call("editor_set_particle_preset", "editor", {"node_path": "P1", "preset": "lava"},
           "probe", "preset is not in the tool's closed set")
    b.call("editor_set_particle_preset", "editor", {"node_path": "NoSuchNode", "preset": "fire"},
           "probe", "node does not exist")
    # --- editor_set_particle_material: 5 ok + 3 probes ----------------------
    for i, args in enumerate([
            {"node_path": "P1", "material_params": {"initial_velocity_min": 40.0, "initial_velocity_max": 90.0}},
            {"node_path": "P2", "material_params": {"gravity": {"x": 0.0, "y": 98.0, "z": 0.0}}},
            {"node_path": "P3", "material_params": {"scale_min": 0.5, "scale_max": 2.0}},
            {"node_path": "P4", "material_params": {"spread": 45.0, "damping_min": 1.0, "damping_max": 2.0}},
            {"node_path": "P5", "material_params": {"color": {"r": 0.2, "g": 0.9, "b": 0.4, "a": 1.0}}}], 1):
        b.call("editor_set_particle_material", "editor", args,
               note="set_particle_material call %d/5" % i)
    b.call("editor_set_particle_material", "editor", {"node_path": "P1", "material_params": {}},
           "probe", "material_params must not be empty")
    b.call("editor_set_particle_material", "editor", {"node_path": "P1", "material_params": {"no_such_param": 1.0}},
           "probe", "the process material has no such parameter")
    b.call("editor_set_particle_material", "editor", {"node_path": "P1", "material_params": "spread"},
           "probe", "material_params is typed object, not string")
    # --- editor_set_particle_color_gradient: 5 ok + 4 probes ----------------
    for i, args in enumerate([
            {"node_path": "P1", "colors": [{"offset": 0.0, "color": {"r": 1.0, "g": 1.0, "b": 0.0, "a": 1.0}},
                                           {"offset": 1.0, "color": {"r": 1.0, "g": 0.0, "b": 0.0, "a": 0.0}}]},
            {"node_path": "P2", "colors": [{"offset": 0.0, "color": {"r": 0.5, "g": 0.5, "b": 0.5, "a": 1.0}},
                                           {"offset": 0.5, "color": {"r": 1.0, "g": 1.0, "b": 1.0, "a": 0.6}},
                                           {"offset": 1.0, "color": {"r": 0.0, "g": 0.0, "b": 0.0, "a": 0.0}}]},
            {"node_path": "P3", "colors": [{"offset": 0.0, "color": {"r": 0.3, "g": 0.5, "b": 1.0, "a": 1.0}},
                                           {"offset": 1.0, "color": {"r": 0.9, "g": 0.1, "b": 1.0, "a": 0.0}}]},
            {"node_path": "P4", "colors": [{"offset": 0.0, "color": {"r": 1.0, "g": 0.6, "b": 0.1, "a": 1.0}},
                                           {"offset": 1.0, "color": {"r": 0.6, "g": 0.1, "b": 0.1, "a": 0.0}}]},
            {"node_path": "P5", "colors": [{"offset": 0.0, "color": {"r": 0.6, "g": 0.7, "b": 1.0, "a": 0.7}},
                                           {"offset": 1.0, "color": {"r": 0.6, "g": 0.7, "b": 1.0, "a": 0.7}}]}], 1):
        b.call("editor_set_particle_color_gradient", "editor", args,
               note="set_particle_color_gradient call %d/5" % i)
    b.call("editor_set_particle_color_gradient", "editor", {"node_path": "P1", "colors": []},
           "probe", "an empty colour-stop array is refused")
    b.call("editor_set_particle_color_gradient", "editor", {"node_path": "P1", "colors": "red"},
           "probe", "colors is typed array, not string")
    b.call("editor_set_particle_color_gradient", "editor",
           {"node_path": "P1", "colors": [{"offset": 0.0, "color": {"r": 1.0, "g": 0.0, "b": 0.0, "a": 1.0}},
                                          {"offset": 0.0, "color": {"r": 0.0, "g": 1.0, "b": 0.0, "a": 1.0}}]},
           "probe", "two stops at the same offset")
    b.call("editor_set_particle_color_gradient", "editor", {"node_path": "NoSuchNode", "colors": [
        {"offset": 0.0, "color": {"r": 1.0, "g": 0.0, "b": 0.0, "a": 1.0}}]},
        "probe", "node does not exist")
    # --- editor_get_particle_info: 5 ok + 1 probe ---------------------------
    for i, args in enumerate([{"node_path": p} for p in ("P1", "P2", "P3", "Seed", "P1")], 1):
        b.call("editor_get_particle_info", "editor", args,
               note="read back the presets/params/gradients written above (%d/5)" % i)
    b.call("editor_get_particle_info", "editor", {"node_path": "NoSuchNode"},
           "probe", "node does not exist")
    b.call("editor_get_particle_info", "editor", {"node_path": "P1"}, "setup",
           "read-back: the final state of P1 (preset + params + gradient) from the engine")

    b.readback_of("editor_create_particles", "editor_get_particle_info",
                  "the created system must answer as a GPUParticles2D with its own "
                  "process_material", "\"process_material_slot\": \"process_material\"")
    b.readback_of("editor_set_particle_preset", "editor_get_particle_info",
                  "the fire preset's own amount/lifetime must be the node's real values",
                  "\"amount\"")
    b.readback_of("editor_set_particle_material", "editor_get_particle_info",
                  "the parameter editor_set_particle_material wrote must be in the read-back "
                  "parameter set", "\"damping_min\": 1.0")
    b.readback_of("editor_set_particle_color_gradient", "editor_get_particle_info",
                  "the gradient stops the tool wrote must come back as the material's colours",
                  "\"color_stop_count\": 2")
    b.write()


def build_h9():
    b = Batch("h9", "ex_rec", "h9-task113")
    b.call("running_game_get_scene_tree", "game", {}, "setup",
           "the running scene the recorder drives")
    b.call("running_game_get_node_properties", "game",
           {"node_path": "Player", "properties": ["position"]}, "setup",
           "read-back #1: the player's position before any input")
    # Five create -> replay(explicit) -> stop rounds, plus the two boundaries.
    for i in range(5):
        b.call("running_game_create_input_recording", "game", {},
               note="create call %d/5" % (i + 1))
        b.sleep("game", 120, "let the recorder node enter the tree")
        b.call("running_game_play_input_recording", "game",
               {"events": [{"type": "key", "keycode": "Right", "pressed": True, "time_ms": 0},
                           {"type": "key", "keycode": "Right", "pressed": False, "time_ms": 250}],
                "speed": 1.0},
               note="play call %d/5 with an explicit two-event recording; the injected keys are "
                    "what the recorder in the same run captures" % (i + 1))
        b.sleep("game", 900, "the replay injects its last event and the recorder sees both")
        b.call("running_game_stop_input_recording", "game", {},
               note="stop call %d/5: the events the recorder captured are returned" % (i + 1))
        b.sleep("game", 150, "settle")
    b.call("running_game_get_node_properties", "game",
           {"node_path": "Player", "properties": ["position"]}, "setup",
           "the player really moved while the recorded keys were down")
    b.call("running_game_set_node_property", "game",
           {"node_path": "Player", "property": "position", "value": {"x": 100.0, "y": 300.0}}, "setup",
           "reset the player so the replay's own motion is measurable")
    b.call("running_game_get_node_properties", "game",
           {"node_path": "Player", "properties": ["position"]}, "setup",
           "read-back #2: the player is back at (100,300) before the replay")
    # The replay that must be visible: no `events` argument -> the recording made
    # by the stop above is replayed into the running game.
    b.call("running_game_play_input_recording", "game", {"speed": 1.0},
           note="the create->stop->play chain: this replays the recording just stopped (no "
                "`events` argument)")
    b.sleep("game", 1200, "the replay injects the recorded keys; the player script moves on them")
    b.call("running_game_get_node_properties", "game",
           {"node_path": "Player", "properties": ["position"]}, "setup",
           "read-back #3: the replay moved the player (position.x > 100)")
    # boundaries
    b.call("running_game_create_input_recording", "game", {}, "setup",
           "start a recording that the boundary below then finds already running")
    b.call("running_game_create_input_recording", "game", {},
           "probe", "a recording is already running in this process")
    b.call("running_game_stop_input_recording", "game", {}, "setup", "close that session")
    b.call("running_game_play_input_recording", "game", {"events": []},
           "probe", "an empty event array is refused (nothing to replay)")
    b.call("running_game_stop_input_recording", "game", {},
           "edge", "stop with nothing recording is a documented success (there is nothing to collect)")
    b.call("running_game_get_node_properties", "game",
           {"node_path": "Player", "properties": ["position"]}, "setup",
           "read-back #4: the position after the boundary calls")

    b.readback_of("running_game_create_input_recording", "running_game_stop_input_recording",
                  "the stop call's answer carries the events of the session create started "
                  "(event_count > 0)", "\"recording\": false")
    b.readback_of("running_game_play_input_recording", "running_game_get_node_properties",
                  "the player's position after the create->stop->play chain is not the reset "
                  "(100,300): the replay really drove the game", "\"position\"")
    b.readback_of("running_game_stop_input_recording", "running_game_get_node_properties",
                  "the position read after the stop differs from the position read before the "
                  "session (the recorded keys moved the player)", "\"position\"")
    b.write()


BUILDERS = {"h4": build_h4, "h5": build_h5, "h6": build_h6, "h9": build_h9}


def sessions():
    for key in ("h4", "h5", "h6", "h9"):
        BUILDERS[key]()
    return 0


def main(argv):
    if len(argv) < 2 or argv[1] not in ("prepare", "sessions"):
        print(__doc__)
        return 2
    return prepare() if argv[1] == "prepare" else sessions()


if __name__ == "__main__":
    sys.exit(main(sys.argv))
