#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""TASK-113 item D: reclassify the twenty H4/H5/H6/H9 tools the register called
structurally unreachable.

The register's own rule (its `_comment`) is: delete nothing silently - record the
demonstration under `reclassified`. This script appends one entry per tool with
the run that demonstrated it.

Usage:
    python recovery/work/task113/reclassify.py --write
"""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
REGISTRY = os.path.join(ROOT, "tools", "tool_coverage_unreachable.json")

H4_WHY = ("the corpus has no navigation data, but the family needs only a project that ships a "
          "NavigationRegion2D with an outline-bearing NavigationPolygon plus a player: "
          "projects/_exercises/ex_nav carries scenes/main.tscn built by the engine's own API "
          "(mk_probe.gd). All six members ran for real: editor_setup_navigation_region / "
          "editor_setup_navigation_agent create their nodes, editor_set_navigation_layers writes "
          "the mask editor_get_navigation_info reads back, editor_bake_navigation_mesh really "
          "baked (the first bake moved 155978 pixels in the editor viewport and reported "
          "baked:true with polygon_count 1), and running_game_move_player_to_target moved the "
          "player along the engine's own NavigationServer path in all five calls "
          "(distance_traveled 178.1/399.3/181.4/166.6/461.2).")
H5_WHY = ("no game has any sound, but the family's subjects are the editor process's own "
          "AudioServer and one AudioStreamPlayer2D node: projects/_exercises/ex_audio ships five "
          "real RIFF WAVE assets (generated by the TASK-113 generator and imported by --import). "
          "All six members ran: five buses were added (Music/Sfx/Ambient/Voice/Ui), five effects "
          "attached to them, five players created, and editor_get_audio_bus_layout / "
          "editor_get_audio_info read the engine's own bus list (including the volume_db -6.0 "
          "editor_set_audio_bus_property wrote) back.")
H6_WHY = ("the corpus has no particles, but the family needs only GPUParticles2D nodes and a "
          "ParticleProcessMaterial: projects/_exercises/ex_particles ships a scene with one "
          "GPUParticles2D and editor_create_particles makes five more. All five members ran: two "
          "presets (fire/smoke/...), five process-material parameter writes and five colour "
          "gradients, each read back by editor_get_particle_info (params, colors and "
          "color_stop_count).")
H9_WHY = ("input recording needs the three-step create -> play/stop session, which the corpus "
          "never opened: projects/_exercises/ex_rec carries a player script whose motion is driven "
          "by the key events the replay injects. All three members ran five times each: every "
          "create/stop round captured the two key events the explicit replay injected "
          "(event_count 2), and the final create -> stop -> play chain (no `events` argument) "
          "moved the player from x=100 to x=151 with a recomputed pixel diff of 1152 pixels - the "
          "replay really drives the running game.")

FAMILIES = [
    ("H4", "h4-task113", "runs/_exercises/ex_nav/h4-task113/trace-editor.jsonl", H4_WHY,
     ["editor_bake_navigation_mesh", "editor_get_navigation_info", "editor_set_navigation_layers",
      "editor_setup_navigation_agent", "editor_setup_navigation_region"]),
    ("H4", "h4-task113", "runs/_exercises/ex_nav/h4-task113/trace-game.jsonl", H4_WHY,
     ["running_game_move_player_to_target"]),
    ("H5", "h5-task113", "runs/_exercises/ex_audio/h5-task113/trace-editor.jsonl", H5_WHY,
     ["editor_add_audio_bus", "editor_add_audio_bus_effect", "editor_add_audio_player",
      "editor_get_audio_bus_layout", "editor_get_audio_info", "editor_set_audio_bus_property"]),
    ("H6", "h6-task113", "runs/_exercises/ex_particles/h6-task113/trace-editor.jsonl", H6_WHY,
     ["editor_create_particles", "editor_get_particle_info", "editor_set_particle_color_gradient",
      "editor_set_particle_material", "editor_set_particle_preset"]),
    ("H9", "h9-task113", "runs/_exercises/ex_rec/h9-task113/trace-game.jsonl", H9_WHY,
     ["running_game_create_input_recording", "running_game_play_input_recording",
      "running_game_stop_input_recording"]),
]


def main(argv):
    write = "--write" in argv
    with io.open(REGISTRY, "r", encoding="utf-8") as handle:
        doc = json.load(handle)
    known = {item["tool"] for item in doc.get("reclassified") or []}
    added = []
    for code, batch, evidence, why, tools in FAMILIES:
        for tool in tools:
            if tool in known:
                continue
            doc.setdefault("reclassified", []).append({
                "tool": tool, "from": code, "why": why, "evidence": evidence,
                "batch": batch, "task": "TASK-113",
            })
            added.append(tool)
    doc["_reclassified_comment"] = (
        doc.get("_reclassified_comment", "") +
        " TASK-113 batches h4/h5/h6/h9 added the remaining 20 (all of H4, H5 and H6, and the "
        "three recording tools of H9): their preconditions are project-shipped assets built by "
        "the engine's own API, and each tool ran at least six times with a boundary probe.")
    print("added %d reclassified entries: %s" % (len(added), ", ".join(added)))
    if write and added:
        with io.open(REGISTRY, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(json.dumps(doc, ensure_ascii=False, indent=2) + "\n")
        print("wrote %s" % REGISTRY)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
