//! DR-73 ③(a) / D280(a) / T10A-7 — the controlled analysis file gets a **sidecar**.
//!
//! `TASK-SMOKE-T10-ACCEPTANCE.md` T10A-7 (minor, disclosure accuracy) found that
//! `.spec/hof-rs/tasks/TASK-SMOKE-T10-evidence/analysis/redaction_defect.txt`
//! still carries the environment dump it is evidence *about*: `HOH_ARTIFACT_DIR=…`,
//! `HOH_GAME_ROUTE=…`, `HOH_HOH_BIN=…`, `HOH_ITERATION=1`, `HOH_MODEL_API_KEY=` and
//! a `PATH` tail containing the user name.  No credential value ever leaked, so
//! this is a disclosure rule, not a credential rule — but the round's own report
//! claimed that directory held no environment dump, and the claim was false.
//!
//! **The original is evidence of the defect and is never touched** (D280(a), and
//! D276's rule that in-place rewriting of frozen/read evidence is over).  The
//! requirement "the products carry no environment value" is satisfied by a
//! generated sidecar next to it, and the tests below pin both halves: the original
//! is byte-identical, and the sidecar has nothing left.

use std::fmt::Write as _;
use std::path::PathBuf;

/// The controlled analysis file, and the sidecar generated beside it.
const SOURCE: &str = ".spec/hof-rs/tasks/TASK-SMOKE-T10-evidence/analysis/redaction_defect.txt";
const SIDECAR: &str =
    ".spec/hof-rs/tasks/TASK-SMOKE-T10-evidence/analysis/redaction_defect.redacted.txt";

/// The byte identity of the original when this test was written.  It is pinned so
/// the sidecar can never be "produced" by editing the source: any change to the
/// original makes this test red and has to be an explicit decision.
const SOURCE_SHA256: &str = "201ae32e970c6b396ef309aacad45e986d972a6f48fbe122a46d58b31d949466";
const SOURCE_BYTES: usize = 2035;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hasher
        .finalize()
        .iter()
        .fold(String::new(), |mut out, byte| {
            let _ = write!(out, "{byte:02x}");
            out
        })
}

/// The redacted body of one recorded occurrence line.
///
/// The original records the raw **JSON-escaped** form of an environment dump, so
/// its `\n`/`\r` are backslash escapes rather than line endings: the assignment
/// scanner cannot see them as boundaries, and — more importantly — a line of the
/// product must not be able to carry an environment value into the sidecar at all.
/// The value between the quotes is therefore replaced wholesale, and the two
/// lines' only surviving content is the structure of the finding.
fn sidecar_line(line: &str) -> String {
    let Some(open) = line.find('\'') else {
        return line.to_string();
    };
    let Some(close) = line.rfind('\'') else {
        return line.to_string();
    };
    if close <= open {
        return line.to_string();
    }
    let mut out = String::new();
    out.push_str(&line[..open + 1]);
    out.push_str("<redacted by TASK-DR73: the recorded environment dump is not repeated here>");
    out.push_str(&line[close..]);
    out
}

/// Build the sidecar from the original: the occurrence lines with their recorded
/// dumps replaced, every other line through the production assignment redactor
/// (so the `SIMULATION` block's `HOH_*=` values are erased too).
fn sidecar_text(original: &str) -> String {
    let mut body = String::new();
    for line in original.split_inclusive('\n') {
        let trimmed = line.trim_end_matches('\n');
        let newline = &line[trimmed.len()..];
        let rewritten = if trimmed.starts_with('\'') {
            sidecar_line(trimmed)
        } else {
            hof_rs::runtime::secrets::redact_secret_assignments(trimmed)
        };
        body.push_str(&rewritten);
        body.push_str(newline);
    }
    assert!(
        !body.is_empty(),
        "the sidecar must be a generated product, not an empty file"
    );
    format!(
        "# DR-73 ③(a) — redacted sidecar of `redaction_defect.txt` (T10A-7).\n\
         #\n\
         # The original is the frozen evidence for the T10A-2/F-T10-1 defect and is NOT edited.\n\
         # This copy is generated by `tests/round_artifacts_sidecar.rs::build_sidecar` for the\n\
         # disclosure requirement \"the products carry no environment value\" (D280(a)).\n\
         # What is removed here: every `HOH_*` assignment's value, the `PATH` tail, and the raw\n\
         # environment dump recorded verbatim in the two `--- attemptN occurrence M ---` lines.\n\
         # The finding that survives — which trajectory broke, at which byte, and why — is below.\n\
         \n{body}"
    )
}

fn build_sidecar() -> (PathBuf, PathBuf, Vec<u8>, Vec<u8>) {
    let root = repo_root();
    let source_path = root.join(SOURCE);
    let sidecar_path = root.join(SIDECAR);
    let original = std::fs::read(&source_path)
        .unwrap_or_else(|error| panic!("the controlled analysis file must exist: {error}"));
    assert_eq!(
        original.len(),
        SOURCE_BYTES,
        "the original's byte length is pinned; a different length means it was edited"
    );
    assert_eq!(
        sha256_hex(&original),
        SOURCE_SHA256,
        "the original's bytes are pinned; the defect evidence must not be rewritten"
    );
    let text = String::from_utf8(original.clone()).expect("the analysis file is UTF-8");
    let sidecar = sidecar_text(&text);
    std::fs::write(&sidecar_path, sidecar.as_bytes())
        .unwrap_or_else(|error| panic!("the sidecar must be writable: {error}"));
    (source_path, sidecar_path, original, sidecar.into_bytes())
}

/// The sidecar is generated from the original, and the original keeps every byte.
#[test]
fn the_sidecar_is_generated_and_the_original_is_untouched() {
    let (source_path, sidecar_path, before, _) = build_sidecar();

    let after = std::fs::read(&source_path).unwrap();
    assert_eq!(
        after, before,
        "{source_path:?} must be byte-identical to what it was before the sidecar was built"
    );
    assert_eq!(
        sha256_hex(&after),
        SOURCE_SHA256,
        "the original's bytes are what the defect record means"
    );

    let sidecar = std::fs::read(&sidecar_path).unwrap();
    assert!(!sidecar.is_empty(), "{sidecar_path:?} must not be empty");
    let text = String::from_utf8(sidecar).expect("the sidecar is UTF-8");
    // It is a *sidecar*: a new file beside the original, not a replacement.
    assert_ne!(sidecar_path, source_path);
    assert!(
        text.contains("redaction_defect.txt"),
        "the sidecar must name the file it is generated from"
    );
    assert!(
        text.contains("412870"),
        "the defect's own finding (the byte offset that broke the trajectory) must survive"
    );
    assert!(
        text.contains("not edited") || text.contains("NOT edited"),
        "the sidecar must record that the original is untouched"
    );
    // The recorded dumps really are gone — the marker the generator writes stands
    // where each of the original's occurrence lines recorded one.  Without this a
    // "sidecar" that simply copied the file would pass every other check.
    assert_eq!(
        text.matches("<redacted by TASK-DR73:").count(),
        original_occurrences(),
        "every recorded occurrence must be replaced by the marker, not copied"
    );
    assert!(
        !text.contains("HOH_GAME_ROUTE=F:"),
        "no occurrence line may carry its recorded value:\n{text}"
    );
}

/// How many `--- attemptN occurrence M ---` records the original carries.  The
/// file starts with a UTF-8 BOM, so the first header does not start the line.
fn original_occurrences() -> usize {
    std::fs::read_to_string(repo_root().join(SOURCE))
        .expect("the original is readable")
        .lines()
        .filter(|line| line.contains("attempt") && line.contains("occurrence"))
        .count()
}

/// DR-76 ⑥: the assignment names the **original** really carries.
///
/// The DR-73 check looped over a hard-coded `(marker, leaked)` table and only
/// fired when the *sidecar* contained the marker.  The sidecar contains none of
/// those markers — the occurrence lines are replaced wholesale — so every pair
/// was vacuous: the loop had nothing to inspect, and a sidecar that simply copied
/// the original's dumps would still have passed it.  (Two of the six names,
/// `HOH_ARTIFACT_DIR=` and `PATH=`, are not even in the original; the acceptance's
/// A6 found that too.)  The check below derives its subject from the original's
/// own bytes instead.
fn assignment_names(original: &str) -> Vec<String> {
    let mut names: Vec<String> = Vec::new();
    let mut rest = original;
    while let Some(start) = rest.find("HOH_") {
        let after = &rest[start..];
        let end = after
            .find(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))
            .unwrap_or(after.len());
        let name = &after[..end];
        if after[end..].starts_with('=') && !names.iter().any(|existing| existing == name) {
            names.push(name.to_string());
        }
        rest = &after[end.max(1)..];
    }
    names
}

/// The value of `NAME=` on one line, up to the first boundary the recorded
/// encoding uses (whitespace, a backslash escape, a quote, a `;`), or `None` when
/// the line does not carry the assignment.
fn assignment_value_after(line: &str, name: &str) -> Option<String> {
    let start = line.find(name)? + name.len();
    let rest = &line[start..];
    if rest.starts_with("<redacted>") {
        return Some("<redacted>".to_string());
    }
    let end = rest
        .find(|character: char| {
            character.is_whitespace() || character == '\\' || character == '"' || character == ';'
        })
        .unwrap_or(rest.len());
    Some(rest[..end].to_string())
}

/// The disclosure requirement: no environment value survives into the sidecar.
#[test]
fn the_sidecar_carries_no_environment_value_and_no_user_name() {
    let (_, sidecar_path, _, _) = build_sidecar();
    let text = std::fs::read_to_string(&sidecar_path).unwrap();
    let original =
        std::fs::read_to_string(repo_root().join(SOURCE)).expect("the original is readable");

    // DR-76 ⑥: every assignment the original records must lose its value.
    // `HOH_MODEL_API_KEY=` survives in the sidecar's own `SIMULATION` block, where
    // the original already carried `<redacted>`; that is the shape the check
    // has to allow, and "the value is the redaction marker" is exactly what it
    // asserts.  A sidecar that copied an occurrence line instead of replacing it
    // carries `HOH_GAME_ROUTE=F:\\…` and reddens here.
    let names = assignment_names(&original);
    assert!(
        !names.is_empty(),
        "the original must carry the assignments this check is about, or it proves nothing"
    );
    let mut inspected = 0usize;
    for name in &names {
        let marker = format!("{name}=");
        for line in text.lines() {
            let Some(value) = assignment_value_after(line, &marker) else {
                continue;
            };
            inspected += 1;
            assert!(
                value.starts_with("<redacted"),
                "the recorded value of `{marker}` survived the sidecar: `{value}` in {line:?}"
            );
        }
    }
    assert!(
        inspected > 0,
        "no assignment was inspected at all, so the loop above is vacuous again: {text}"
    );
    // …and the specific claim A6 falsified is recorded as a fact: the two names
    // that made the DR-73 table vacuous are not in the original to begin with.
    for absent in ["HOH_ARTIFACT_DIR=", "PATH="] {
        assert!(
            !original.contains(absent),
            "`{absent}` is not a literal of the original; a check keyed on it can never fire, \
             which is why the DR-73 loop was vacuous"
        );
    }
    // The disclosure itself: no user-name path and no environment dump.
    assert!(
        !text.contains("C:\\"),
        "no absolute Windows path may survive:\n{text}"
    );
    assert!(
        !text.contains("node_modules"),
        "no `PATH` element may survive:\n{text}"
    );
    assert!(
        !text.contains("moonbit-hof-rs"),
        "no repository path may survive:\n{text}"
    );
    assert!(
        !text.contains("<redacted>;"),
        "neither the escaped `;`-joined `PATH` tail nor the environment dump may survive:\n{text}"
    );
    // The scan really saw the file: the values were there to be removed.
    for survived in ["HOH_GAME_ROUTE=", "HOH_MODEL_API_KEY="] {
        assert!(
            original.contains(survived),
            "the fixture must really carry `{survived}`, or this test proves nothing"
        );
        assert!(
            !text.contains(&format!("{survived}F:")),
            "`{survived}` kept its value: {text}"
        );
    }
}
