# TASK-078: apply final confidence rules and build EXTRACTION-MANIFEST.md
import json, os, collections

ROOT = r'C:\Users\wyl\AppData\Local\Temp\mcp-recovery'
W = os.path.join(ROOT, 'work')
ST = os.path.join(ROOT, 'staging')

recs = [json.loads(l) for l in open(os.path.join(W, 'reconstruction.jsonl'), encoding='utf-8')]

# --- final confidence rules (objective evidence over heuristics) ---
for r in recs:
    if r['n_failed'] >= 10:
        if r['conf'] != 'low':
            r['notes'].append('DOWNGRADED_TO_LOW(%d failed edits)' % r['n_failed'])
        r['conf'] = 'low'
    elif r['n_failed'] > 0 and r['conf'] == 'high':
        r['conf'] = 'mid'
        r['notes'].append('DOWNGRADED_FROM_HIGH(%d failed edits)' % r['n_failed'])

PS1 = {}
try:
    for x in json.load(open(os.path.join(W, 'ps1-parse.json'), encoding='utf-8')):
        PS1[x['rel']] = x
except Exception:
    pass

for r in recs:
    if r['rel'].lower().endswith('.ps1') and r['rel'] in PS1:
        pe = PS1[r['rel']]['parseErrors']
        r['ps1_parse_errors'] = pe
        if pe:
            r['notes'].append('PS1_PARSE_ERRORS(%d)' % pe)
            if r['conf'] == 'high':
                r['conf'] = 'mid'
    if r['rel'].lower().endswith('.py') and r['wrote']:
        import ast
        try:
            ast.parse(open(os.path.join(ST, r['rel']), encoding='utf-8').read())
            r['py_parses'] = True
        except Exception as e:
            r['py_parses'] = False
            r['notes'].append('PY_PARSE_ERROR')
            r['conf'] = 'low'

with open(os.path.join(W, 'reconstruction.jsonl'), 'w', encoding='utf-8', newline='\n') as f:
    for r in recs:
        f.write(json.dumps(r, ensure_ascii=False) + '\n')

def rel_of(p):
    low = p.replace('/', '\\').lower()
    pre = 'f:\\rustprojects\\godot-mcp-pro\\code\\godot\\'
    return p.replace('/', '\\')[len(pre):] if low.startswith(pre) else '__EXTERNAL__'

inrepo = [r for r in recs if rel_of(r['path']) != '__EXTERNAL__']
ext = [r for r in recs if rel_of(r['path']) == '__EXTERNAL__']

def dsrc(r):
    s = r.get('last_src')
    if not s:
        return '(none)'
    return '%s seq=%s t=%s' % (s['f'].split('_session')[0][:36], s['seq'], s['time'])

def line(r):
    return '| `%s` | %s | %s | %s | %s | %s | %s |' % (
        r['rel'].replace('\\', '/'), r['chosen'] or '-', {'high': '**高**', 'mid': '中', 'low': '低'}[r['conf']],
        '?' if r['bytes'] is None else r['bytes'],
        {True: 'no', False: 'MISSING'}.get(r['wrote'], 'MISSING') if r['miss_tail'] == 'no' else r['miss_tail'],
        r['read_cov_pct'], dsrc(r))

by = collections.defaultdict(list)
for r in inrepo:
    parts = r['rel'].split('\\')
    key = '\\'.join(parts[:2]) if len(parts) > 2 else ('\\'.join(parts[:1]))
    by[key].append(r)

ORDER = ['modules\\mcp_server', 'core', 'editor', 'modules\\mono', 'scene', 'modules\\gdscript',
         'drivers', 'platform', 'servers', 'main', 'misc', 'thirdparty', 'tests', 'docs']
def order_key(k):
    return (ORDER.index(k) if k in ORDER else 99, k)

out = []
out.append('# EXTRACTION-MANIFEST - TASK-078 (payload extraction from the .dsh session transcripts)')
out.append('')
out.append('Generated by `scripts/extract_pass1.py` -> `scripts/extract_pass2_v3.py` -> `scripts/fix_candidates.py` -> `scripts/build_manifest.py`.')
out.append('Payload source: `C:\\Users\\wyl\\AppData\\Local\\Temp\\mcp-recovery\\transcripts\\*.jsonl` (178 files, 594,263,811 B).')
out.append('Staging root: `C:\\Users\\wyl\\AppData\\Local\\Temp\\mcp-recovery\\staging\\`. Nothing was written to `F:`.')
out.append('')
out.append('## 0. Column meanings')
out.append('')
out.append('* `path` - staging-relative path. In-repo paths are relative to `F:\\RustProjects\\godot-mcp-pro\\code\\godot\\`')
out.append('  (the deleted tree); anything else is parked under `__external\\<drive><abs path>`.')
out.append('* `cand` - which candidate produced the staged bytes:')
out.append('  `write-chain` = write payload + replayed edits; `read-epoch` = version-coherent read-window merge;')
out.append('  `read-complete` = a single complete read that supersedes the chain; `-` = nothing usable.')
out.append('* `conf` - **高** = direct `write` (or write+edit replay that a later complete read confirms);')
out.append('  **中** = rebuilt from `read` windows and/or an edit chain that cannot be replayed with zero failures;')
out.append('  **低** = only fragments (diff/partial reads) or a replay with many failed edits / parse errors.')
out.append('* `bytes` - size of the staged file. `tail` - `no` = complete, `yes` = end of file missing,')
out.append('  `partial-only` = interior lines missing but the tail is present.')
out.append('* `cov%` - union coverage of the read windows against the newest observed `totalLines`.')
out.append('* `src` - transcript file (basename prefix) + record `seq`/`time` of the last authoritative payload.')
out.append('')
tot = collections.Counter(r['conf'] for r in recs)
totb = sum(r['bytes'] or 0 for r in recs)
out.append('## 1. Totals')
out.append('')
out.append('| metric | value |')
out.append('|---|---|')
out.append('| distinct payload paths | %d |' % len(recs))
out.append('| staged files | %d |' % sum(1 for r in recs if r['wrote']))
out.append('| staged bytes | %d |' % totb)
out.append('| high confidence | %d |' % tot['high'])
out.append('| medium confidence | %d |' % tot['mid'])
out.append('| low confidence | %d |' % tot['low'])
out.append('| no payload at all | %d |' % sum(1 for r in recs if not r['wrote']))
out.append('| in-repo paths | %d |' % len(inrepo))
out.append('| out-of-repo paths | %d |' % len(ext))
out.append('| preserved alternative candidates | %d |' % sum(1 for r in recs if r['alt_saved']))
out.append('| history versions written | %d |' % sum(r['hist_files'] for r in recs))
out.append('')
out.append('## 2. Per-directory summary (in-repo)')
out.append('')
out.append('| dir | paths | staged | bytes | high | mid | low |')
out.append('|---|---|---|---|---|---|---|')
for k in sorted(by, key=order_key):
    g = by[k]
    c = collections.Counter(r['conf'] for r in g)
    out.append('| %s | %d | %d | %d | %d | %d | %d |' % (k, len(g), sum(1 for r in g if r['wrote']),
               sum(r['bytes'] or 0 for r in g), c['high'], c['mid'], c['low']))
out.append('')
out.append('## 3. Per-file table (in-repo, sorted by path)')
out.append('')
out.append('| path | cand | conf | bytes | tail | cov% | src |')
out.append('|---|---|---|---|---|---|---|')
for r in sorted(inrepo, key=lambda r: r['rel'].lower()):
    out.append(line(r))
out.append('')
out.append('## 4. Out-of-repo payloads (one-off scripts, %TEMP% work dirs, the hof-rs repo)')
out.append('')
out.append('These are staged under `staging\\__external\\` with the original directory structure preserved.')
out.append('They are helper/one-off material, not part of the deleted module tree, but they are kept because')
out.append('several in-repo artifacts were produced by them (e.g. `check_exit_propagation.py`).')
out.append('')
out.append('| path | cand | conf | bytes | tail | cov% | src |')
out.append('|---|---|---|---|---|---|---|')
for r in sorted(ext, key=lambda r: r['rel'].lower()):
    out.append(line(r))
out.append('')

# focused sections
def find(suffix):
    return [r for r in recs if r['rel'].lower().replace('\\', '/').endswith(suffix)]

out.append('## 5. Contract files (the "three-piece" contract set) and its generator')
out.append('')
out.append('| path | cand | conf | bytes | tail | cov% | n_write | n_edit | failed | notes |')
out.append('|---|---|---|---|---|---|---|---|---|---|')
for suf in ('docs/tools_list.renamed.json', 'docs/tool-rename-map.json', 'docs/tool-groups.json',
            'docs/tool-groups-added.json', 'docs/tool-groups-b3.json', 'scripts/gen_renamed_contract.py',
            'docs/tools_list.json'):
    for r in find(suf):
        out.append('| `%s` | %s | %s | %s | %s | %s | %d | %d | %d | %s |' % (
            r['rel'].replace('\\', '/'), r['chosen'] or '-', r['conf'], r['bytes'], r['miss_tail'],
            r['read_cov_pct'], r['n_write'], r['n_edit'], r['n_failed'], '; '.join(r['notes'])[:220]))
out.append('')
out.append('## 6. Engine-patch files (the three engine patches)')
out.append('')
out.append('| path | cand | conf | bytes | tail | cov% | n_write | n_edit | failed | notes |')
out.append('|---|---|---|---|---|---|---|---|---|---|')
for suf in ('core/config/project_settings.cpp', 'core/config/project_settings.h',
            'editor/editor_node.cpp', 'modules/mono/csharp_script.cpp', 'modules/mono/csharp_script.h'):
    for r in find(suf):
        out.append('| `%s` | %s | %s | %s | %s | %s | %d | %d | %d | %s |' % (
            r['rel'].replace('\\', '/'), r['chosen'] or '-', r['conf'], r['bytes'], r['miss_tail'],
            r['read_cov_pct'], r['n_write'], r['n_edit'], r['n_failed'], '; '.join(r['notes'])[:220]))
out.append('')
out.append('## 7. The six tool scripts')
out.append('')
out.append('| path | cand | conf | bytes | tail | cov% | n_write | n_edit | failed | ps1 parse errors | py parses | notes |')
out.append('|---|---|---|---|---|---|---|---|---|---|---|---|')
for suf in ('check_engine_anchor.ps1', 'mcp_evidence_guard.ps1', 'mcp_watch_run.ps1',
            'check_exit_propagation.py', 'check_tautologies.py', 'check_hardcoded_counts.py'):
    for r in find(suf):
        out.append('| `%s` | %s | %s | %s | %s | %s | %d | %d | %d | %s | %s | %s |' % (
            r['rel'].replace('\\', '/'), r['chosen'] or '-', r['conf'], r['bytes'], r['miss_tail'],
            r['read_cov_pct'], r['n_write'], r['n_edit'], r['n_failed'],
            r.get('ps1_parse_errors', '-'), r.get('py_parses', '-'), '; '.join(r['notes'])[:200]))
out.append('')
out.append('## 8. Risk list - staged bytes that must NOT be trusted verbatim')
out.append('')
out.append('Every path whose staged bytes are `low`, incomplete, or produced by a replay with failures.')
out.append('')
out.append('| path | cand | conf | bytes | tail | failed edits | notes |')
out.append('|---|---|---|---|---|---|---|')
risk = [r for r in recs if r['conf'] == 'low' or r['miss_tail'] != 'no' or r['n_failed']]
risk.sort(key=lambda r: (r['conf'] != 'low', -r['n_failed'], r['rel'].lower()))
for r in risk:
    out.append('| `%s` | %s | %s | %s | %s | %d | %s |' % (r['rel'].replace('\\', '/'), r['chosen'] or '-',
               r['conf'], r['bytes'], r['miss_tail'], r['n_failed'], '; '.join(r['notes'])[:200]))
out.append('')
out.append('## 9. Payloads with no usable file body')
out.append('')
for r in sorted([r for r in recs if not r['wrote']], key=lambda r: r['rel'].lower()):
    out.append('* `%s` - %s' % (r['rel'].replace('\\', '/'), '; '.join(r['notes'])[:200]))
out.append('')
out.append('## 10. Companion artifacts (declared, none of them on F:)')
out.append('')
out.append('* `staging\\__history\\<path>\\<NNNN>_<src>_seq<S>_<sha8>.bak` - every superseded version (%d files).' % sum(r['hist_files'] for r in recs))
out.append('* `staging\\__candidates\\<path>.{write-chain,read-epoch}.txt` - the rejected candidate wherever the two differed (%d files).' % sum(1 for r in recs if r['alt_saved']))
out.append('* `staging\\__diffs\\` - diff-class payloads (git diff/show/status), one `.diff` + one `.cmd.txt` per captured command, plus `INDEX.md`.')
out.append('* `staging\\__payload-index\\` - the raw machine-readable spool (`events-{write,edit,read,diff,termfile,termdump,termlog,misc}.jsonl`).')
out.append('* `work\\` - intermediate analysis output (`reconstruction.jsonl`, `gen-runs.jsonl`, `ps1-parse.json`, `swaps.json`).')
out.append('* `scripts\\` - the extraction scripts (see the report for the inventory).')
out.append('')

with open(os.path.join(ROOT, 'EXTRACTION-MANIFEST.md'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(out) + '\n')
print('manifest lines =', len(out))
print('manifest bytes =', os.path.getsize(os.path.join(ROOT, 'EXTRACTION-MANIFEST.md')))
print('conf:', dict(tot))
