#!/usr/bin/env python3
"""DR-71 ④: compute every byte claim in the frozen-evidence record, from facts.

"Self-report vs byte fact" failed two consecutive batches: DR-69's redaction note
was wrong about what it had cut, and DR-70's correction of that note stated the
two replaced run lengths wrongly again (52 -> 28 and 23 -> 28, not 54 -> 30 and
25 -> 30).  Both times the prose carried hand-written numbers next to bytes that
a command could have measured.  This script is the fix for the *class*: the record
contains a generated block, this script writes it, and the shipped test
`tests/byte_claims.rs` recomputes every value independently and fails if the block
drifts — so the numbers cannot be typed by hand any more.

Facts, and where each one comes from:

  * `original_*`   the committed blob at `dc9d350` (== `3adab37^`), i.e. before
                   DR-69 touched anything;
  * `dr69_*`       the blob DR-69 committed (`3adab37`);
  * `worktree_*`   the file as it is on disk right now (the DR-70 surgical edit);
  * `*_replaced_bytes` / `*_marker_bytes`
                   the single substituted byte run, computed as the removed and
                   inserted spans between the two revisions (longest common
                   prefix/suffix).  These are the two numbers that were wrong.

Usage (offline; loopback filesystem and git objects only):

    python scripts/byte_claims.py --emit     # print the block
    python scripts/byte_claims.py --check    # exit 1 if a document's block drifted
    python scripts/byte_claims.py --write    # rewrite the block in each document
"""

import argparse
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DUMP = ".spec/hof-rs/tasks/TASK-SMOKE-T9-evidence/experiment/dev1_commands.txt"
ORIGINAL_BLOB = "dc9d350"
DR69_BLOB = "3adab37"

BEGIN = "<!-- DR-71-BYTE-CLAIMS-BEGIN -->"
END = "<!-- DR-71-BYTE-CLAIMS-END -->"

DOCUMENTS = [
    ".spec/hof-rs/tasks/TASK-SMOKE-T9-evidence/REDACTION.md",
    ".spec/hof-rs/tasks/TASK-DR70-REPORT.md",
    ".spec/hof-rs/tasks/TASK-DR71-REPORT.md",
]

HEADER = (
    "DR-71 generated byte claims - written by `python scripts/byte_claims.py --write`, "
    "re-computed by tests/byte_claims.rs.  Do not edit by hand."
)


def git_blob(rev, path):
    """The committed bytes of `path` at `rev` (never the working tree)."""
    completed = subprocess.run(
        ["git", "-C", REPO, "show", "%s:%s" % (rev, path)],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        raise SystemExit(
            "FATAL: `git show %s:%s` failed (%s); the byte facts cannot be computed "
            "without the historical blobs.\n%s"
            % (rev, path, completed.returncode, completed.stderr.decode("utf-8", "replace"))
        )
    return completed.stdout


def records(data):
    """The record count: non-empty LF-separated segments."""
    return sum(1 for line in data.split(b"\n") if line.strip())


def dir_b_p(data):
    return data.count(b"dir /b -p")


def substitution(older, newer):
    """The single replaced byte run: (removed, inserted).

    Longest common prefix and suffix; whatever is left in the middle is the run
    the redaction substituted.  A multi-run difference would show up here as an
    impossible pair, which is why the caller also records the byte totals.
    """
    limit = min(len(older), len(newer))
    head = 0
    while head < limit and older[head] == newer[head]:
        head += 1
    tail = 0
    while tail < limit - head and older[len(older) - 1 - tail] == newer[len(newer) - 1 - tail]:
        tail += 1
    return len(older) - head - tail, len(newer) - head - tail


def facts():
    original = git_blob(ORIGINAL_BLOB, DUMP)
    dr69 = git_blob(DR69_BLOB, DUMP)
    current_path = os.path.join(REPO, DUMP)
    with open(current_path, "rb") as handle:
        current = handle.read()

    dr69_removed, dr69_inserted = substitution(original, dr69)
    work_removed, work_inserted = substitution(original, current)

    ordered = [
        ("path", DUMP),
        ("original_blob", ORIGINAL_BLOB),
        ("original_bytes", len(original)),
        ("original_cr", original.count(b"\r")),
        ("original_lf", original.count(b"\n")),
        ("original_records", records(original)),
        ("original_dir_b_p", dir_b_p(original)),
        ("dr69_blob", DR69_BLOB),
        ("dr69_bytes", len(dr69)),
        ("dr69_delta_bytes", len(dr69) - len(original)),
        ("dr69_lf", dr69.count(b"\n")),
        ("dr69_cr", dr69.count(b"\r")),
        ("dr69_records", records(dr69)),
        ("dr69_dir_b_p", dir_b_p(dr69)),
        ("dr69_replaced_bytes", dr69_removed),
        ("dr69_marker_bytes", dr69_inserted),
        ("worktree_bytes", len(current)),
        ("worktree_delta_bytes", len(current) - len(original)),
        ("worktree_cr", current.count(b"\r")),
        ("worktree_lf", current.count(b"\n")),
        ("worktree_records", records(current)),
        ("worktree_dir_b_p", dir_b_p(current)),
        ("worktree_replaced_bytes", work_removed),
        ("worktree_marker_bytes", work_inserted),
    ]
    return ordered


def block_text(newline):
    lines = [HEADER]
    lines.extend("%s = %s" % (key, value) for key, value in facts())
    return newline.join(lines) + newline


def split_document(raw, begin=BEGIN, end=END):
    """(before, block, after) around a marker pair that owns a whole line.

    The markers must be **standalone lines**: a report may legitimately quote them
    inside prose or inside a pasted `--emit` sample, and such a quotation must not
    be mistaken for the generated block (that mistake cost this batch one repair).
    """
    text = raw.decode("utf-8")
    newline = "\r\n" if "\r\n" in text else "\n"
    lines = text.split(newline)
    start = end_index = None
    for index, line in enumerate(lines):
        if line.strip() == begin and start is None:
            start = index
        elif line.strip() == end and start is not None:
            end_index = index
            break
    if start is None or end_index is None:
        return None
    block = newline.join(lines[start + 1 : end_index])
    before = newline.join(lines[: start + 1])
    after = newline.join(lines[end_index:])
    return before, block, after


def document_block(raw):
    parts = split_document(raw)
    if parts is None:
        raise SystemExit("FATAL: a standalone DR-71 byte-claims marker pair is missing")
    _, block, _ = parts
    return block.strip("\r\n")


def check():
    failures = []
    for relative in DOCUMENTS:
        path = os.path.join(REPO, relative)
        with open(path, "rb") as handle:
            raw = handle.read()
        newline = "\r\n" if b"\r\n" in raw else "\n"
        expected = block_text(newline).strip("\r\n").strip()
        actual = document_block(raw)
        if actual != expected:
            failures.append(relative)
            sys.stderr.write("MISMATCH %s\n" % relative)
            sys.stderr.write("--- document ---\n%s\n" % actual)
            sys.stderr.write("--- computed ---\n%s\n" % expected)
        else:
            sys.stdout.write("ok %s\n" % relative)
    return 1 if failures else 0


def write():
    for relative in DOCUMENTS:
        path = os.path.join(REPO, relative)
        with open(path, "rb") as handle:
            raw = handle.read()
        parts = split_document(raw)
        if parts is None:
            raise SystemExit("FATAL: %s has no standalone DR-71 byte-claims marker pair" % relative)
        before, _, after = parts
        newline = "\r\n" if b"\r\n" in raw else "\n"
        updated = before + newline + block_text(newline) + after
        with open(path, "wb") as handle:
            handle.write(updated.encode("utf-8"))
        sys.stdout.write("wrote %s\n" % relative)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--emit", action="store_true", help="print the generated block")
    group.add_argument("--check", action="store_true", help="fail if a document drifted")
    group.add_argument("--write", action="store_true", help="rewrite the blocks")
    args = parser.parse_args()
    if args.emit:
        sys.stdout.write(BEGIN + "\n" + block_text("\n") + END + "\n")
        return 0
    if args.check:
        return check()
    write()
    return 0


if __name__ == "__main__":
    sys.exit(main())
